# Generated by Django 3.0.7 on 2020-06-27 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="standbyTimeData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_code", models.IntegerField()),
                ("standby_time", models.IntegerField(null=True)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("operating_status", models.CharField(max_length=60, null=True)),
                ("operating_status_start", models.DateTimeField(null=True)),
                ("operating_status_end", models.DateTimeField(null=True)),
                (
                    "Facility_FastPass_Status",
                    models.CharField(max_length=60, null=True),
                ),
                ("Facility_FastPass_Start", models.DateTimeField(null=True)),
                ("Facility_FastPass_End", models.DateTimeField(null=True)),
            ],
        ),
    ]
