# Generated by Django 3.0.7 on 2020-06-28 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='standbyTimeDataTDL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.IntegerField()),
                ('standby_time', models.IntegerField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('operating_status', models.CharField(max_length=60, null=True)),
                ('operating_status_start', models.TimeField(null=True)),
                ('operating_status_end', models.TimeField(null=True)),
                ('facility_fastpass_status', models.CharField(max_length=60, null=True)),
                ('facility_fastpass_start', models.TimeField(null=True)),
                ('facility_fastpass_end', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='standbyTimeDataTDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.IntegerField()),
                ('standby_time', models.IntegerField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('operating_status', models.CharField(max_length=60, null=True)),
                ('operating_status_start', models.TimeField(null=True)),
                ('operating_status_end', models.TimeField(null=True)),
                ('facility_fastpass_status', models.CharField(max_length=60, null=True)),
                ('facility_fastpass_start', models.TimeField(null=True)),
                ('facility_fastpass_end', models.TimeField(null=True)),
            ],
        ),
    ]
