# Generated by Django 3.0.7 on 2020-06-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standbytime", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standbytimedata",
            old_name="Facility_FastPass_End",
            new_name="facility_fastpass_end",
        ),
        migrations.RenameField(
            model_name="standbytimedata",
            old_name="Facility_FastPass_Start",
            new_name="facility_fastpass_start",
        ),
        migrations.RenameField(
            model_name="standbytimedata",
            old_name="Facility_FastPass_Status",
            new_name="facility_fastpass_status",
        ),
    ]
