# Generated by Django 3.0.7 on 2020-08-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standbytimedatatdl',
            options={'verbose_name': '東京ディズニーランド待ち時間データ', 'verbose_name_plural': '東京ディズニーランド待ち時間データリスト'},
        ),
        migrations.AlterModelOptions(
            name='standbytimedatatds',
            options={'verbose_name': '東京ディズニーシー待ち時間データ', 'verbose_name_plural': '東京ディズニーシー待ち時間データリスト'},
        ),
    ]
