# Generated by Django 3.0.7 on 2020-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0002_auto_20200817_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standbytimedatatdl',
            name='standby_time',
            field=models.FloatField(null=True),
        ),
    ]
