# Generated by Django 3.0.7 on 2020-06-27 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("standbytime", "0003_auto_20200627_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standbytimedata",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
