# Generated by Django 3.0.7 on 2020-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0003_auto_20200820_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standbytimedatatds',
            name='standby_time',
            field=models.FloatField(null=True),
        ),
    ]
