# Generated by Django 3.0.7 on 2020-09-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0004_auto_20200825_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standbytimedatatdl',
            old_name='facility_code',
            new_name='facilityCode',
        ),
        migrations.RenameField(
            model_name='standbytimedatatds',
            old_name='facility_code',
            new_name='facilityCode',
        ),
    ]
