# Generated by Django 3.0.7 on 2020-06-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0005_auto_20200628_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standbytimedata',
            name='facility_fastpass_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='standbytimedata',
            name='facility_fastpass_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='standbytimedata',
            name='operating_status_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='standbytimedata',
            name='operating_status_start',
            field=models.TimeField(null=True),
        ),
    ]
