# Generated by Django 3.0.7 on 2020-11-17 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0006_auto_20200921_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='averageStandbyTimeDataTDL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityCode', models.TextField(max_length=10)),
                ('standby_time', models.FloatField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '東京ディズニーランド平均待ち時間データ',
                'verbose_name_plural': '東京ディズニーランド平均待ち時間データリスト',
            },
        ),
        migrations.CreateModel(
            name='averageStandbyTimeDataTDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityCode', models.TextField(max_length=10)),
                ('standby_time', models.FloatField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '東京ディズニーシー平均待ち時間データ',
                'verbose_name_plural': '東京ディズニーシー平均待ち時間データリスト',
            },
        ),
    ]
