# Generated by Django 3.0.7 on 2020-12-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0007_averagestandbytimedatatdl_averagestandbytimedatatds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagestandbytimedatatdl',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='averagestandbytimedatatds',
            name='time',
            field=models.TimeField(),
        ),
    ]
