# Generated by Django 3.0.7 on 2020-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0008_auto_20201214_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagestandbytimedatatdl',
            name='a',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averagestandbytimedatatds',
            name='a',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
