# Generated by Django 3.0.7 on 2020-12-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standbytime', '0009_auto_20201214_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagestandbytimedatatdl',
            name='a',
        ),
        migrations.RemoveField(
            model_name='averagestandbytimedatatds',
            name='a',
        ),
    ]
