# Generated by Django 3.0.7 on 2020-09-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='facilityCode',
            field=models.TextField(max_length=10),
        ),
    ]
