# Generated by Django 3.0.7 on 2020-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': '全ユーザお気に入りアトラクション', 'verbose_name_plural': '全ユーザお気に入りアトラクションリスト'},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_id',
            new_name='facility_code',
        ),
    ]
