# Generated by Django 3.0.7 on 2020-08-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200817_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='submit_date',
            new_name='submit_time',
        ),
    ]
