# Generated by Django 3.0.7 on 2020-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20200817_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='park_type',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
